export * from './Home/index'
export * from './Annotaciya/index'

// 7-klass
export * from './Panler-bazasi/7-klass/Joybar-jumısları/tekst/index'
export * from './Panler-bazasi/7-klass/Joybar-jumısları/videoo/index'
export * from './Panler-bazasi/7-klass/Laboratoriya-shınıǵıwları/tekst/index'
export * from './Panler-bazasi/7-klass/Laboratoriya-shınıǵıwları/vertual/index'
export * from './Panler-bazasi/7-klass/Laboratoriya-shınıǵıwları/videoo/index'
export * from './Panler-bazasi/7-klass/Máseleler/tekst/index'
export * from './Panler-bazasi/7-klass/Máseleler/videoo/index'
export * from './Panler-bazasi/7-klass/Prezentaciyalar/tekst/index'
export * from './Panler-bazasi/7-klass/Prezentaciyalar/videoo/index'
export * from './Panler-bazasi/7-klass/Ámeliy-shınıǵıwlar/tekst/index'
export * from './Panler-bazasi/7-klass/Ámeliy-shınıǵıwlar/videoo/index'
export * from './Panler-bazasi/7-klass/Óz-betinshe/tekst/index'
export * from './Panler-bazasi/7-klass/Óz-betinshe/videoo/index'

// 8-klass
export * from './Panler-bazasi/8-klass/Joybar-jumısları/tekst/index'
export * from './Panler-bazasi/8-klass/Joybar-jumısları/videoo/index'
export * from './Panler-bazasi/8-klass/Laboratoriya-shınıǵıwları/tekst/index'
export * from './Panler-bazasi/8-klass/Laboratoriya-shınıǵıwları/vertual/index'
export * from './Panler-bazasi/8-klass/Laboratoriya-shınıǵıwları/videoo/index'
export * from './Panler-bazasi/8-klass/Máseleler/tekst/index'
export * from './Panler-bazasi/8-klass/Máseleler/videoo/index'
export * from './Panler-bazasi/8-klass/Prezentaciyalar/tekst/index'
export * from './Panler-bazasi/8-klass/Prezentaciyalar/videoo/index'
export * from './Panler-bazasi/8-klass/Ámeliy-shınıǵıwlar/tekst/index'
export * from './Panler-bazasi/8-klass/Ámeliy-shınıǵıwlar/videoo/index'
export * from './Panler-bazasi/8-klass/Óz-betinshe/tekst/index'
export * from './Panler-bazasi/8-klass/Óz-betinshe/videoo/index'

// 9-klass
export * from './Panler-bazasi/9-klass/Joybar-jumısları/tekst/index'
export * from './Panler-bazasi/9-klass/Joybar-jumısları/videoo/index'
export * from './Panler-bazasi/9-klass/Laboratoriya-shınıǵıwları/tekst/index'
export * from './Panler-bazasi/9-klass/Laboratoriya-shınıǵıwları/vertual/index'
export * from './Panler-bazasi/9-klass/Laboratoriya-shınıǵıwları/videoo/index'
export * from './Panler-bazasi/9-klass/Máseleler/tekst/index'
export * from './Panler-bazasi/9-klass/Máseleler/videoo/index'
export * from './Panler-bazasi/9-klass/Prezentaciyalar/tekst/index'
export * from './Panler-bazasi/9-klass/Prezentaciyalar/videoo/index'
export * from './Panler-bazasi/9-klass/Ámeliy-shınıǵıwlar/tekst/index'
export * from './Panler-bazasi/9-klass/Ámeliy-shınıǵıwlar/videoo/index'
export * from './Panler-bazasi/9-klass/Óz-betinshe/tekst/index'
export * from './Panler-bazasi/9-klass/Óz-betinshe/videoo/index'

// 10-klass
export * from './Panler-bazasi/10-klass/Joybar-jumısları/tekst/index'
export * from './Panler-bazasi/10-klass/Joybar-jumısları/videoo/index'
export * from './Panler-bazasi/10-klass/Laboratoriya-shınıǵıwları/tekst/index'
export * from './Panler-bazasi/10-klass/Laboratoriya-shınıǵıwları/vertual/index'
export * from './Panler-bazasi/10-klass/Laboratoriya-shınıǵıwları/videoo/index'
export * from './Panler-bazasi/10-klass/Máseleler/tekst/index'
export * from './Panler-bazasi/10-klass/Máseleler/videoo/index'
export * from './Panler-bazasi/10-klass/Prezentaciyalar/tekst/index'
export * from './Panler-bazasi/10-klass/Prezentaciyalar/videoo/index'
export * from './Panler-bazasi/10-klass/Ámeliy-shınıǵıwlar/tekst/index'
export * from './Panler-bazasi/10-klass/Ámeliy-shınıǵıwlar/videoo/index'
export * from './Panler-bazasi/10-klass/Óz-betinshe/tekst/index'
export * from './Panler-bazasi/10-klass/Óz-betinshe/videoo/index'

// 11-klass
export * from './Panler-bazasi/11-klass/Joybar-jumısları/tekst/index'
export * from './Panler-bazasi/11-klass/Joybar-jumısları/videoo/index'
export * from './Panler-bazasi/11-klass/Laboratoriya-shınıǵıwları/tekst/index'
export * from './Panler-bazasi/11-klass/Laboratoriya-shınıǵıwları/vertual/index'
export * from './Panler-bazasi/11-klass/Laboratoriya-shınıǵıwları/videoo/index'
export * from './Panler-bazasi/11-klass/Máseleler/tekst/index'
export * from './Panler-bazasi/11-klass/Máseleler/videoo/index'
export * from './Panler-bazasi/11-klass/Prezentaciyalar/tekst/index'
export * from './Panler-bazasi/11-klass/Prezentaciyalar/videoo/index'
export * from './Panler-bazasi/11-klass/Ámeliy-shınıǵıwlar/tekst/index'
export * from './Panler-bazasi/11-klass/Ámeliy-shınıǵıwlar/videoo/index'
export * from './Panler-bazasi/11-klass/Óz-betinshe/tekst/index'
export * from './Panler-bazasi/11-klass/Óz-betinshe/videoo/index'